 <?php
 // module/Blog/view/blog/block/add.phtml:

 $title = 'Add new block';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
 <a href="<?php echo $this->url('admBl');?>">Back to block</a>
</p>
 <?php
 $form->setAttribute('action', $this->url('admBl', array('action' => 'add')));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('name_bl')); echo '<br/>';
 echo $this->formSubmit($form->get('submit'));echo '<br/>';
 echo $this->form()->closeTag();