<?php
// module/Blog/view/blog/block/edit.phtml:

$title = 'Edit block';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
 <a href="<?php echo $this->url('admBl');?>">Back to blocks</a>
</p>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
 'admBl',
 array(
     'action' => 'edit',
     'id'     => $this->id,
 )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('name_bl')); echo '<br/>';
echo $this->formSubmit($form->get('submit')); echo '<br/>';
echo $this->form()->closeTag();