<?php
// module/Blog/view/blog/category/add.phtml:

$title = 'Add new category';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('admCat');?>">Back to categorys</a>
</p>
<?php
$form->setAttribute('action', $this->url('admCat', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('name_cat')); echo '<br/>';
echo $this->formRow($form->get('id_block')->setValueOptions($block)); echo '<br/>';
echo $this->formSubmit($form->get('submit'));echo '<br/>';
echo $this->form()->closeTag();