<?php
// module/Blog/view/blog/post/index.phtml:

$title = 'My posts';
$this->headTitle($title);
?>
<div class="admindex">
    <p>
     <a href="<?php echo $this->url('adm');?>">Back to adm</a>
    </p>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <p>
     <a href="<?php echo $this->url('admPost', array('action'=>'add'));?>">Add new post</a>
    </p>
    
    <table class="table">
    <tr>
     <th>Title</th>
     <th>Category</th>
     <th>Block</th>
     <th>&nbsp;</th>
    </tr>
    <?php foreach ($paginator as $post) : ?>
    <tr>
     <td><?php echo $this->escapeHtml($post->title);?></td>
     <td><?php echo $this->escapeHtml($post->name_cat);?></td>
     <td><?php echo $this->escapeHtml($post->name_bl);?></td>
     <td>
         <a href="<?php echo $this->url('admPost',
             array('action'=>'edit', 'id' => $post->id));?>">Edit</a>
         <a href="<?php echo $this->url('admPost',
             array('action'=>'delete', 'id' => $post->id));?>">Delete</a>
     </td>
    </tr>
    <?php endforeach; ?>
    </table>
</div>
<?php
// add at the end of the file after the table
echo $this->paginationControl(
 // the paginator object
 $this->paginator,
 // the scrolling style
 'sliding',
 // the partial to use to render the control
 'partial/paginator.phtml',
 // the route to link to when a user clicks a control link
 array(
     'route' => $_SERVER[REQUEST_URI],
 )
);
?>