<div id="page">
    <?php foreach ($paginator as $post) : ?>
        <div class="post">
            <div class="title">
                <p>
                    <a href="<?php echo $this->url('postId', array(
                                                                'action'=>'postId', 
                                                                'id' => $post->id, 
                                                                'title' => $post->title
                                                        ));?>">
                        <?php echo $this->escapeHtml($post->title); ?>
                    </a>
                </p>
            </div>
            <div class="content">
                <p><?php echo $this->escapeHtml($post->content); ?></p>
            </div>
        </div>
        <hr class="line" />
    <?php endforeach; ?>
</div>
 <?php
 // add at the end of the file after the table
 echo $this->paginationControl(
     // the paginator object
     $this->paginator,
     // the scrolling style
     'sliding',
     // the partial to use to render the control
     'partial/paginator.phtml',
     // the route to link to when a user clicks a control link
     array(
         'route' => $_SERVER[REQUEST_URI],
     )
 );
 ?>